service: expatcinema

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-west-1
  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 's3:PutObject'
      Resource:
        - 'arn:aws:s3:::expatcinema-scrapers-output/*'
    - Effect: 'Allow'
      Action:
        - 's3:PutObject'
      Resource:
        - 'arn:aws:s3:::expatcinema-public/*'

functions:
  scrapers:
    handler: handler.scrapers
    timeout: 120
    environment:
      DEBUG: '*,-resolve'

resources:
  Resources:
    ScrapersOutputBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: expatcinema-scrapers-output
        PublicAccessBlockConfiguration:
          BlockPublicAcls: true
          BlockPublicPolicy: true
          IgnorePublicAcls: true
          RestrictPublicBuckets: true
    PublicBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: expatcinema-public
        CorsConfiguration:
          CorsRules:
            -
              AllowedOrigins:
                - '*'
              AllowedHeaders:
                - '*'
              AllowedMethods:
                - GET
              MaxAge: 3000
    PublicBucketPolicy:
      Type: AWS::S3::BucketPolicy
      DependsOn: PublicBucket
      Properties:
        Bucket: expatcinema-public
        PolicyDocument:
          Statement:
            - Principal: "*"
              Action:
                - s3:GetObject
              Effect: Allow
              Sid: "AddPerm"
              Resource: arn:aws:s3:::expatcinema-public/*
