version: 0.2

phases:
  pre_build:
    commands:
      - echo Installing npm packages
      - cd spa/
      - yarn
  build:
    commands:
      - CI=true yarn test
      - yarn build
artifacts:
  files:
    - '**/*'
  base-directory: build

