name: Backend

on:
  push: # Runs on pushes targeting the default branch.
    branches:
      - main
    paths:
      - 'backend/**'
      - '.github/workflows/backend.yml'
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

jobs:
  synth:
    name: Synth
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Deploy
        env:
          DYNAMODB_MOVIE_METADATA: ${{ secrets.DYNAMODB_MOVIE_METADATA }}
        run: |
          cd backend/
          pnpm cdk deploy --require-approval never
