name: Cloud

on:
  push: # Runs on pushes targeting the default branch
    branches:
      - main
    paths:
      - 'cloud/**'
      - '.github/workflows/cloud.yml'
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

jobs:
  deploy_to_dev:
    name: Deploy to Development
    environment: development
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - name: Deploy to Development
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
          OMDB_API_KEY: ${{ secrets.OMDB_API_KEY }}
          GOOGLE_CUSTOM_SEARCH_ID: ${{ secrets.GOOGLE_CUSTOM_SEARCH_ID }}
          GOOGLE_CUSTOM_SEARCH_API_KEY: ${{ secrets.GOOGLE_CUSTOM_SEARCH_API_KEY }}
          DYNAMODB_MOVIE_METADATA: ${{ secrets.DYNAMODB_MOVIE_METADATA }}
          SCRAPERS: ${{ vars.SCRAPERS }}
          SCRAPEOPS_API_KEY: ${{ secrets.SCRAPEOPS_API_KEY }}
        run: |
          cd cloud/
          pnpm deploy:ci --stage dev

  deploy_to_production:
    name: Deploy to Production
    environment: production
    runs-on: ubuntu-latest
    needs: [deploy_to_dev]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile
      - name: Deploy to Production
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
          OMDB_API_KEY: ${{ secrets.OMDB_API_KEY }}
          GOOGLE_CUSTOM_SEARCH_ID: ${{ secrets.GOOGLE_CUSTOM_SEARCH_ID }}
          GOOGLE_CUSTOM_SEARCH_API_KEY: ${{ secrets.GOOGLE_CUSTOM_SEARCH_API_KEY }}
          DYNAMODB_MOVIE_METADATA: ${{ secrets.DYNAMODB_MOVIE_METADATA }}
          SCRAPERS: ${{ vars.SCRAPERS }}
          SCRAPEOPS_API_KEY: ${{ secrets.SCRAPEOPS_API_KEY }}
        run: |
          cd cloud/
          pnpm deploy:ci --stage prod
