name: Cloud

on:
  push:
    branches:
      - main
    paths:
      - 'cloud/**'
      - '.github/workflows/cloud.yml'

jobs:
  build:
    name: Install Dependencies, Build, and Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: |
          cd cloud/
          yarn install --frozen-lockfile

  # deploy_to_dev:
  #   name: Deploy to Development
  #   environment: development
  #   runs-on: ubuntu-latest
  #   needs: [build]

  #   steps:
  #     - name: Deploy to Production
  #       env:
  #         SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
  #         AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  #         AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  #         DEBUG: ${{ secrets.DEBUG }}
  #       run: |
  #         cd cloud/
  #         yarn deploy:ci --stage dev

  deploy_to_production:
    name: Deploy to Production
    environment: production
    runs-on: ubuntu-latest
    needs: [build]
    # needs: [deploy_to_dev]

    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: |
          cd cloud/
          yarn install --frozen-lockfile
      - name: Deploy to Production
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DEBUG: ${{ secrets.DEBUG }}
        run: |
          cd cloud/
          yarn deploy:ci --stage prod
