name: Cloud

on:
  push:
    branches:
      - master
    paths:
      - 'cloud/**'
      - '.github/workflows/cloud.yml'

jobs:
  build:
    name: Build, Test and Deploy

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: |
          cd cloud/
          yarn install --frozen-lockfile
      - name: Deploy
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DEBUG: ${{ secrets.DEBUG }}
        run: |
          cd cloud/
          yarn deploy:ci
