name: Cloud

on:
  push: # Runs on pushes targeting the default branch.
    branches:
      - main
    paths:
      - 'cloud/**'
      - '.github/workflows/cloud.yml'
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

defaults:
  run:
    working-directory: cloud/

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
      - name: Install Dependencies
        working-directory: .
        run: pnpm install --frozen-lockfile
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: CDK Bootstrap
        run: pnpm run bootstrap
      - name: CDK Deploy
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
          OMDB_API_KEY: ${{ secrets.OMDB_API_KEY }}
          GOOGLE_CUSTOM_SEARCH_ID: ${{ secrets.GOOGLE_CUSTOM_SEARCH_ID }}
          GOOGLE_CUSTOM_SEARCH_API_KEY: ${{ secrets.GOOGLE_CUSTOM_SEARCH_API_KEY }}
          SCRAPERS: ${{ secrets.SCRAPERS }}
          SCRAPEOPS_API_KEY: ${{ secrets.SCRAPEOPS_API_KEY }}
        run: pnpm run deploy:ci
