name: Cloud

on:
  push:
    branches:
      - master
    paths:
      - 'cloud/*'
      - '.github/workflows/cloud.yml'

jobs:
  build:
    name: Build, Test and Deploy

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies
        run: |
          cd cloud/
          yarn
      - name: Serverless version
        run: |
          cd cloud
          ./node_modules/.bin/serverless -v
      - name: echo my first environment variable
        env:
          FOO: bar
        run: |
          echo $FOO
      # - name: echo SLACK_WEBHOOK
      #   env:
      #     SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
      #   run: |
      #     echo $SLACK_WEBHOOK
      - name: Deploy
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          cd cloud/
          yarn deploy
