name: SPA

on:
  push:
    branches:
      - master
    paths:
      - 'spa/*'
      - '.github/workflows/spa.yml'

jobs:
  build:
    name: Build, Test and Deploy

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install dependencies
        run: |
          cd spa/
          yarn
      - name: Test
        run: |
          cd spa/
          yarn test
        env:
          CI: true
      - name: Build
        run: |
          cd spa/
          yarn build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@master
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: spa/build
