name: Web

on:
  push:
    branches:
      - master
    paths:
      - 'web/**'
      - '.github/workflows/web.yml'
  schedule:
    - cron: '30 3 * * *' # daily at 3.30 UTC.

jobs:
  build:
    name: Build, Test and Deploy

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install dependencies
        run: |
          cd web/
          yarn install --frozen-lockfile
      - name: Build
        run: |
          cd web/
          yarn build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@36e7d6be3ae491bda245af50d04b012d956c1f14
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: gh-pages
          FOLDER: web/public
