name: Web

on:
  push:
    branches:
      - main
    paths:
      - 'web/**'
      - '.github/workflows/web.yml'
  schedule:
    - cron: '30 3 * * *' # daily at 3.30 UTC.

jobs:
  build:
    name: Build, Test and Deploy

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Build
        run: |
          cd web/
          yarn build
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.4.0
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          branch: gh-pages
          folder: web/out
          clean: true
          single-commit: true
